### ISSUE TITLE
Adding the NSFileProtectionComplete entitlement via platform config

### ISSUE THREAD

**Issue by BrianJVarley** [dpa99c/cordova-custom-config-example#1]
@dpa99c I installed cordova-custom-config plugin into a cordova project, in the confix.xml I added the following permission to turn on Data Protection in the iOS platform plist.

I wasn't sure from the plugin docs but is this the correct syntax to add the Data Protection entitlement?

`<platform name="ios">
        <config-file platform="ios" target="*-Info.plist" parent="NSFileProtectionComplete">
        <dict>
            <key>DataProtectionClass</key>
            <true/>
        </dict>
        </config-file>
    </platform>`

**Comment by dpa99c** [comment]
According to [this answer on stackoverflow](http://stackoverflow.com/a/8727842/777265), the target plist format should be:

```
<plist version="1.0">
    <dict>
        <key>DataProtectionClass</key>
        <string>NSFileProtectionComplete</string>
    </dict>
</plist>
```

To produce this, the config-file block should be:

```
<config-file platform="ios" target="*-Info.plist" parent="DataProtectionClass">
    <string>NSFileProtectionComplete</string>
</config-file>
```

However, as noted in [this question](http://stackoverflow.com/q/36577647/777265), adding the key to the plist may not be enough: you may also need to enable the capability in the project settings.
Currently, this plugin doesn't enable the setting of XCode project capabilities, so you'd need to do that manually in XCode or write a custom hook script to set it in the `project.pxbproj`.

**Comment by BrianJVarley** [comment]
@dpa99c ok thanks for the tip. I'll see if adding the config will suffice.
