### ISSUE TITLE
Disabling back up in an Android platform config

### ISSUE THREAD

**Issue by BrianJVarley** [dpa99c/cordova-custom-config-example#2]
@dpa99c I've had to disable back up in the Android platform and going off this example in the plugin docs:

```
 <config-file target="AndroidManifest.xml" parent="/*">
    <supports-screens
        android:xlargeScreens="false"
        android:largeScreens="false"
        android:smallScreens="false" />
</config-file>
```

It seems this would be the correct syntax to disable the backup permission? In this [link](http://www.tutorialspoint.com/android/android_data_backup.htm) in looks like the child of the <Application>:

```
   <config-file target="AndroidManifest.xml" parent="/*">
        <application android:allowBackup="false"/>
    </config-file>
```

**Comment by dpa99c** [comment]
```
<config-file target="AndroidManifest.xml" parent="/*">
    <application android:allowBackup="false"/>
</config-file>
```

The above would replace the existing <application> block, which you certainly don't want to do. Instead, use a preference to set the attribute value:

```
<preference name="android-manifest/application/@android:allowBackup" value="false" />
```
